package com.lti.service;

import java.util.Properties;

import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.Multipart;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeBodyPart;
import javax.mail.internet.MimeMessage;
import javax.mail.internet.MimeMultipart;

import org.springframework.stereotype.Service;

@Service("adminCancellationMailService")
public class AdminCancellationMailServiceImpl implements AdminCancellationMailService {
	
	public void sendAdminCancellationMail(String emailId, int attachmentNumber, String bookingId, String dateTime, String flightNumber) {

		// Recipient's email ID needs to be mentioned.
		String to = emailId;

		// Sender's email ID needs to be mentioned
		String from = "noreply.starkair@gmail.com";

		// Assuming you are sending email from through gmails smtp
		String host = "smtp.gmail.com";

		// Get system properties
		Properties properties = System.getProperties();

		// Setup mail server
		properties.put("mail.smtp.host", host);
		properties.put("mail.smtp.port", "465");
		properties.put("mail.smtp.ssl.enable", "true");
		properties.put("mail.smtp.auth", "true");

		// Get the Session object.// and pass
		Session session = Session.getInstance(properties, new javax.mail.Authenticator() {

			protected PasswordAuthentication getPasswordAuthentication() {

				return new PasswordAuthentication("noreply.starkair@gmail.com", "starkair@1234");

			}

		});
		// session.setDebug(true);
		try {
			// Create a default MimeMessage object.
			MimeMessage message = new MimeMessage(session);

			// Set From: header field of the header.
			message.setFrom(new InternetAddress(from));

			// Set To: header field of the header.
			message.addRecipient(Message.RecipientType.TO, new InternetAddress(to));

			// Set Subject: header field
			message.setSubject("Cancellation Alert of your flight with Stark Air");

			Multipart multipart = new MimeMultipart();

			

			MimeBodyPart textPart = new MimeBodyPart();

			try {
				
				textPart.setContent("<h2 style=\"color: red;\">Cancellation Alert</h2>\r\n"
						+ "<p>We inform you with regret that your flight with the following details has been cancelled due to some unavoidable circumstances.</p>\r\n"
						+ "<br>\r\n" + "<table>\r\n" + "    <tr>\r\n" + "        <th>Flight Number: </th>\r\n"
						+ "        <td>"+flightNumber+"</td>\r\n" + "    </tr>\r\n" + "    <tr>\r\n"
						+ "        <th>Departure Date and Time: </th>\r\n" + "        <td>"+dateTime+"</td>\r\n" + "    </tr>\r\n"
						+ "\r\n" + "    <tr>\r\n" + "        <th>Number of passengers: </th>\r\n"
						+ "        <td>"+attachmentNumber+"</td>\r\n" + "    </tr>\r\n" + "    <tr>\r\n"
						+ "        <th>Booking ID: </th>\r\n" + "        <td>"+bookingId+"</td> \r\n" + "    </tr>\r\n"
						+ "    </table>\r\n" + "\r\n"
						+ "    <p>Since this flight has been cancelled by Stark Air, we have initiated a full refund against your Booking ID to your payment method. Expect the refund to be complete in 2-5 business days.</p><p>We do express apology for this cancellation which was not at all anticipated.</p>\r\n"
						+ "    <p>--------This is an autogenerated email. Please do not reply.-------------</p>\r\n"
						+ "    <br>\r\n"
						+ "    <p>Warm Regards,<br>Customer Care,<br>Internet Ticketing.<br>Stark Air</p>\r\n" + "    ",
						"text/html");
				;
				multipart.addBodyPart(textPart);
				for(int i =1;i<=attachmentNumber;i++) {
					
					
				}

			} catch (Exception e) {

				e.printStackTrace();

			}

			message.setContent(multipart);

			System.out.println("sending...");
			// Send message
			Transport.send(message);
			System.out.println("Sent message successfully....");
		} catch (MessagingException mex) {
			mex.printStackTrace();
		}

	}
	

}
