package com.lti.service;

import java.io.File;
import java.io.IOException;
import java.util.Properties;

import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.Multipart;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeBodyPart;
import javax.mail.internet.MimeMessage;
import javax.mail.internet.MimeMultipart;

import org.springframework.stereotype.Service;

@Service("bookingEmailService")
public class BookingEmailServiceImpl implements BookingEmailService {

	public void sendEmailWithTicket(String emailId, int attachmentNumber, String bookingId, String dateTime, String flightNumber) {

		// Recipient's email ID needs to be mentioned.
		String to = emailId;

		// Sender's email ID needs to be mentioned
		String from = "noreply.starkair@gmail.com";

		// Assuming you are sending email from through gmails smtp
		String host = "smtp.gmail.com";

		// Get system properties
		Properties properties = System.getProperties();

		// Setup mail server
		properties.put("mail.smtp.host", host);
		properties.put("mail.smtp.port", "465");
		properties.put("mail.smtp.ssl.enable", "true");
		properties.put("mail.smtp.auth", "true");

		// Get the Session object.// and pass
		Session session = Session.getInstance(properties, new javax.mail.Authenticator() {

			protected PasswordAuthentication getPasswordAuthentication() {

				return new PasswordAuthentication("noreply.starkair@gmail.com", "starkair@1234");

			}

		});
		// session.setDebug(true);
		try {
			String set = bookingId.substring(0,bookingId.length()-6);
			// Create a default MimeMessage object.
			MimeMessage message = new MimeMessage(session);

			// Set From: header field of the header.
			message.setFrom(new InternetAddress(from));

			// Set To: header field of the header.
			message.addRecipient(Message.RecipientType.TO, new InternetAddress(to));

			// Set Subject: header field
			message.setSubject("Booking Confirmation of your flight with Stark Air");

			Multipart multipart = new MimeMultipart();

			

			MimeBodyPart textPart = new MimeBodyPart();

			try {
				
				textPart.setContent("<h2 style=\"color: blue;\">Ticket Confirmation</h2>\r\n"
						+ "<p>This is to inform you that your booking has been confirmed successfully with the following details.</p>\r\n"
						+ "<br>\r\n" + "<table>\r\n" + "    <tr>\r\n" + "        <th>Flight Number: </th>\r\n"
						+ "        <td>"+flightNumber+"</td>\r\n" + "    </tr>\r\n" + "    <tr>\r\n"
						+ "        <th>Departure Date and Time: </th>\r\n" + "        <td>"+dateTime+"</td>\r\n" + "    </tr>\r\n"
						+ "\r\n" + "    <tr>\r\n" + "        <th>Number of passengers: </th>\r\n"
						+ "        <td>"+attachmentNumber+"</td>\r\n" + "    </tr>\r\n" + "    <tr>\r\n"
						+ "        <th>Booking ID: </th>\r\n" + "        <td>"+set+"</td> \r\n" + "    </tr>\r\n"
						+ "    </table>\r\n" + "\r\n"
						+ "    <p>PFA tickets for each of the added passenger at the time of booking</p>\r\n"
						+ "    <p>--------This is an autogenerated email. Please do not reply.-------------</p>\r\n"
						+ "    <br>\r\n"
						+ "    <p>Warm Regards,<br>Customer Care,<br>Internet Ticketing.<br>Stark Air</p>\r\n" + "    ",
						"text/html");
				;
				multipart.addBodyPart(textPart);
				for(int i =1;i<=attachmentNumber;i++) {
					multipart.addBodyPart(attachment(i,bookingId));
					
				}

			} catch (Exception e) {

				e.printStackTrace();

			}

			message.setContent(multipart);

			System.out.println("sending...");
			// Send message
			Transport.send(message);
			System.out.println("Sent message successfully....");
		} catch (MessagingException mex) {
			mex.printStackTrace();
		}

	}
	
	public MimeBodyPart attachment(int call,String bookingId) throws IOException, MessagingException {
		MimeBodyPart attachmentPart = new MimeBodyPart();
		
		
		
			File f = new File("C:/Gladiator Stark Air Final/gladiator_sme/backend/Generated Ticket/"+bookingId+"Passenger"+call+".pdf");
			attachmentPart.attachFile(f);
		
		return attachmentPart;
	}

}
